quote_db = [
    "Truth is truth, even if no one believes it. A lie is a lie, even if everyone believes it.",
    "When exposing a crime is treated as committing a crime, you are ruled by criminals.",
    "The single greatest tool of oppression is ignorance.",
    "The truth is far more frightening - Nobody is in control.",
    "The world is rudderless.",
    "History is much more the product of chaos than of conspiracy.",
    "When someone whispers, 'Trust no one,' they are inevitably also saying, 'Trust me.'",
    "I have a feeling we're not in Kansas anymore...",
    "Keep your friends close, but your enemies closer.",
    "I am big! It's the pictures that got small...",
    "You can't handle the truth!",
    "Why so serious?",
    "I want to play a game...",
    "With great power comes great responsibility.",
    "I am Shiva, the god of death.",
    "You sit on a throne of lies.",
    "It's the question that drives us, Neo. It's the question that brought you here.",
    "You don't know what it is, but it's there, like a splinter in your mind, driving you mad.",
    "There is no spoon!",
    "The body cannot live without the mind.",
    "One man can stop the motor of the world.",
    "Do not tell truth to power. We'll hammer you.",
    "Secrecy is security, and security is victory.",
]